comment:
  image:
    repository: ivtcrootus/comment
    tag: logging
  service:
    externalPort: 9292

post:
  image:
    repository: ivtcrootus/post
    tag: logging
  service:
    externalPort: 5000

ui:
  image:
    repository: ivtcrootus/ui
    tag: logging
  service:
    externalPort: 9292
