version: "2.0"
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:${VOLUME_PATH}
    networks:
      back_net:
        aliases:
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_EXPOSED_PORT}:9292/tcp
    networks:
      front_net:

  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      back_net:
      front_net:

  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      back_net:
      front_net:

  prometheus:
    image: ${USERNAME}/prometheus
    networks:
      back_net:
      front_net:
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.3.0/24
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.4.0/24
