---
- name: Create gitlabci host
  hosts: localhost
  gather_facts: no

  vars:
    service_account_email:  ansible@docker-ivtcro.iam.gserviceaccount.com
    credentials_file: ./gce-docker-ivtcro-ac15014d0346.json
    project_id: docker-ivtcro
    zone: europe-west1-b

  tasks:

    - name: Create Firewall for http and https
      gce_net:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        name: default
        fwname: "http-server-firewall-rule-allow"
        allowed: tcp:80;tcp:443
        state: "present"
        target_tags:
           - http-server
        src_range: ['0.0.0.0/0']

    - name: Launch instances
      gce:
        instance_names: gitlabci-host
        machine_type: n1-standard-1
        image: ubuntu-1604-xenial
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        disk_size: 100
        zone: "{{ zone }}"
        tags:
           - http-server
           - docker-machine
      register: gce

    - name: Wait for SSH for instances
      wait_for:
        delay: 10
        host: "{{ gce.instance_data[0].public_ip }}"
        port: 22
        state: started
        timeout: 60

    - name: Save host data
      add_host:
        hostname: "{{ gce.instance_data[0].public_ip }}"
        groupname: gce_instance_ip
        public_ip: "{{ gce.instance_data[0].public_ip }}"


- name: Installing SW
  hosts: gce_instance_ip
  become: yes

  roles:
    - role: geerlingguy.docker
      docker_install_compose: True

  tasks:
    - name: create gitlab directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - /srv/gitlab/config
        - /srv/gitlab/data
        - /srv/gitlab/logs

    - name: copy docker-compose file
      template:
        src: ./docker-compose.yml.j2
        dest: /srv/gitlab/docker-compose.yml
        mode: 0644
